export const LESSONS = [
  "Ona tili",
  "Adabiyot",
  "Rus tili",
  "Ingliz tili",
  "Matematika",
  "Geometriya",
  "Algebra",
  "Biologiya",
  "Kimyo",
  "Fizika",
  "Geografiya",
  "Jahon tarixi",
  "O'zbekiston tarixi",
  "Tarbiya",
  "Texnologiya",
  "Informatika",
  "Chizmachilik",
  "Iqtisodiyot",
];
