export const LESSONS = [
  'Ona tili',
  'Adabiyot',
  'Rus tili',
  'Ingliz tili',
  'Algebra',
  'Biologiya',
  'Kimyo',
  'Geografiya',
  'Jahon tarixi',
  "O'zbekiston tarixi",
  'Tarbiya',
  'Texnologiya',
  'Informatika',
  'Chizmachilik',
  'Iqtisodiyot',
];
