export const LESSONS = [
  'Ona tili va adabiyot',
  'Ingliz tili',
  'Rus tili',
  'Matematika',
  'Algebra',
  'Geometriya',
  'Fizika',
  'Kimyo',
  'Biologiya',
  'Geografiya',
  'Tarix',
  'Jamiyatshunoslik',
  'Falsafa',
  'Informatika',
  'Tana tarbiya',
  'San’at/Musiqa',
  'Chizmachilik/Rassomchilik',
  'Texnologiya',
];
